### ISSUE TITLE
feature: do config validation on the configuration files

### ISSUE THREAD

**Issue by emartinez-dev** [emartinez-dev/webserv#18]
### Syntax Checks:

1. **Valid Key-Values**: All keys should have corresponding valid values.

### Semantic Checks:

1. **Required Fields**: Make sure all required fields like `root` for a server or `route` for a location are present.
2. **Unique Fields**: Make sure some fields that should be unique, like `port` number for each `server`, are actually unique.
3. **Valid File Paths**: Check if specified file paths for `root`, `cgi_path`, `index`, and `error_page` exist or are reachable.
4. **Valid IP and Port**: The IP address and port numbers specified should be valid.
5. **Valid Methods**: `allow_methods` should contain valid HTTP methods.

### Value Range Checks:

1. `port`: Should be within the allowable port range (0-65535).

### Extra:

1. **Check for Defaults**: If some non-mandatory fields are not specified, they should be set to their default values.

Each of these checks should be carried out in the order that makes the most sense for the application, and any errors should provide a useful error message to make it as easy as possible for the user to correct the mistake.

**Comment by albertobarriga** [comment]
Check all serves need a root, all locations have a root and route but if is a return location it can don't have a root and the limits ports. And check the cgi_path, it need to be in all serves and be accessible. 775df68
