### ISSUE TITLE
Configuration file features

### ISSUE THREAD

**Issue by emartinez-dev** [emartinez-dev/webserv#2]
In the configuration file, we must be able to do the following:

- [x] Choose the port and host of each 'server'. (1)
- [x] Setup the `server_name` or not. (2)
- [x] The first server in the file will be the default, it will answer the requests that don't belong to another server.
- [x] Setup default error pages. (3)
- [x] Limit client body size (4)
- [x] Setup routes with one or multiple of the following rules/configuration: (5)
     - [x] Define a list of accepted HTTP methods for the route. (6)
     - [x] Define a HTTP redirection (7)
     - [x] Define a directory or a file where the file should be searched ( (for example, if url /kapouet is rooted to /tmp/www, ur kapouet/pouic/toto/pouet is /tmp/www/pouic/toto/pouet) (8)
     - [x] Turn on or off directory listing (9).
     - [x] Set a default file to answer if the request is a directory. (10)
     - [x] Execute CGI based on certain file extension (for example .php) (11)
     - [x] Make the CGI work with POST and GET methods
     - [x] Make the route able to accept uploaded files and configure where they should be saved.

Example for all this text:

```
server {
    listen 8002; (1)
    server_name localhost; (2)
    host 127.0.0.1; (1)
    root docs/fusion_web/; (8)
    client_max_body_size 3000; (4)
    index index.html; (10)
    error_page 404 405 ./4xx.html; (3)
    error_page 500 ./5xx.html; (3)

    location /test { (5)
        allow_methods  DELETE POST GET; (6)
        autoindex off (9);
    }
    
    location /tours { (5)
        autoindex on; (9)
        index tours1.html; (10)
        allow_methods GET POST PUT HEAD; (6)
    }

    location /red { (5)
	return /tours; (7)
    }

    location /cgi-bin { (5)
        root ./; (8)
        allow_methods GET POST DELETE; (6)
        index time.py; (10)
        cgi_path /usr/bin/python3 /bin/bash; (11)
        cgi_ext .py .sh;
    }
}
```

**Comment by albertobarriga** [comment]
I saved the servers in a vector and the first is the last and vice-versa.

**Comment by emartinez-dev** [comment]
I think we should check if the configuration for a server is correct, and if one server of the config file is not correct, it should always return Status code 500 when requested, but it should run
