### ISSUE TITLE
Network setup

### ISSUE THREAD

**Issue by emartinez-dev** [emartinez-dev/webserv#3]
- [x] Socket Initialization:
    - [x] Create Socket: Use the socket() function to create a new socket. You will use this socket to listen for incoming client connections.
    - [x] Socket Options: Use setsockopt() to set various options for the socket. For example, enabling the reuse of local addresses with SO_REUSEADDR.

- [x] Binding and Listening
    - [x] Bind Socket: Utilize the bind() function to bind the socket to a specific address and port, which you'll get from your configuration file.
    - [x] Start Listening: employ the listen() function to mark the socket as a passive socket, where it will be listening for incoming client connections.

- [x] Polling Mechanism
    - [x] Initialize Poll: implement your polling mechanism. You can use poll() or its equivalents. This is where you'll be checking for both read and write events.
    - [x] Non-blocking Mode: Ensure that you use fcntl to set your sockets to non-blocking mode to comply with project requirements.

- [x] Accepting Connections
    - [x] Accept Client: Use accept() within your poll loop to accept incoming client connections. Remember, this must also be non-blocking.
    - [x] Client Socket: Once a client connection is accepted, you'll get a new socket specifically for that client. Add this to your poll array.

- [x] Reading and Writing
    - [x] Data Transmission: use send() and recv() for transmitting data. Make sure these operations are also non-blocking and only occur when poll() indicates that it's okay to read or write.
    - [x] Buffer Management: Efficiently manage your buffers to handle partial reads and writes, especially since you're working in a non-blocking mode.

- [x] Closing Connections
    - [x] Close Socket: When you're done with a client connection (or if an error occurs), use close() to close the socket.
    - [x] Resource Cleanup: Don't forget to clean up any resources that are no longer needed to prevent memory leaks and resource exhaustion.

**Comment by emartinez-dev** [comment]
Useful references:

- [Polling mechanism](https://beej.us/guide/bgnet/html/#poll:~:text=on%20poll().-,7.2%20poll()%E2%80%94Synchronous%20I/O%20Multiplexing,-What%20you%20really)
- [How do web-servers "listen" to IP addresses, interrupt or polling?](https://superuser.com/questions/837933/how-do-web-servers-listen-to-ip-addresses-interrupt-or-polling)

**Comment by emartinez-dev** [comment]
Finished in 3fdef77827a9d7742aa96fa6f5e7a14cad97bfeb

**Comment by jlimonesHer** [comment]
Writing to socket has problems when it can't send the file in the same loop iteration:

Previous version
```cpp
int	Cluster::write_to_socket(pollfd const &connection, Response const &response)
{
	if (send(connection.fd, response.getContent().c_str(), strlen(response.getContent().c_str()), 0) == -1)
	{
		std::cout << "Error writing\n";
		return (0);
	}
	return (1);
```

Almost finished one:
```cpp
int	Cluster::write_to_socket(pollfd const &connection, Response const &response)
{
	//std::cout << "Body: " << response.getContent() << std::endl;
	size_t	pos = 0;
	do {
		pos += send(connection.fd, response.getContent().data() + pos, response.getContent().length() - pos, 0);
	} while (pos < response.getContent().length());
	return (1);
}
```

**Comment by emartinez-dev** [comment]
I also have to implement the timeout for a hanging request

**Comment by emartinez-dev** [comment]
done on 8ec3f4bd608c8d8d3f3f17bf0da6fb998767aad2
